/*
 * This source file was generated by the Gradle 'init' task
 */
package zoo;

import java.util.logging.Level;
import java.util.logging.Logger;
import zoo.Enclosure.*;
import zoo.animal.*;

public class Main {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    // DEMO: This is how you can switch the logging level
    Level level = Level.WARNING;
    Logger logger = Logger.getLogger(Zoo.class.getName());
    // set log level
    logger.setLevel(level);
    for (var h : logger.getParent().getHandlers()) {
      h.setLevel(Level.FINE);
    }

    Zoo zoo = new Zoo();

    MammalHouse mammalHouse = new MammalHouse("Mammals 1");
    Aquarium aquarium = new Aquarium("Aquarium 1");

    Ragdoll catNekoChan = new Ragdoll("Neko Chan");
    Lemur lemurKJ = new Lemur("KJ");
    Trout troutNemo = new Trout("Nemo");

    mammalHouse.add(catNekoChan);
    mammalHouse.add(lemurKJ);
    aquarium.add(troutNemo);

    zoo.addEnclosure(mammalHouse);
    zoo.addEnclosure(aquarium);

    System.out.println(zoo.summary());

    System.out.println("All Animals:");
    zoo.getAllAnimals().forEach(System.out::println);

    System.out.println("\nOnly Mammals:");
    zoo.getAllMammals().forEach(System.out::println);

    // Wrong name
    System.out.println("\nAquarium not found:");
    System.out.println(zoo.findEnclosureByName("Aquarium"));

    System.out.println("\nAquarium found:");
    System.out.println(zoo.findEnclosureByName("Aquarium 1"));

    System.out.println("\nCount of animal types:");
    System.out.println(zoo.countAnimalsByType());

    System.out.println("\ngetting animal by predicate:");
    zoo.getAnimalsByPredicate(animal -> animal instanceof Mammal).forEach(System.out::println);

    System.out.println("\nEnclosures that are too full:");
    System.out.println(zoo.getOvercrowdedEnclosures(1));
  }
}
